const apps = [
  {
    name: 'app',
    title: 'bitty app',
    favicon: './images/app.svg',
    color: '#13e7dd',
    // font: 'Press Start 2P',
    font: 'Geostar Fill',
    // font: 'Share Tech Mono',
  },
  {
    name: 'blog',
    title: 'bitty blog',
    favicon: './images/blog.svg',
    color: '#009BFF',
    font: 'Share Tech Mono',
  },
  {
    name: 'shop',
    title: 'bitty shop',
    favicon: './images/shop.svg',
    color: '#bd6bdd',
    font: 'Monoton',
  },
  {
    name: 'note',
    title: 'bitty note',
    favicon: './images/note.svg',
    color: '#ece63d',
    font: 'Permanent Marker',
  },
  {
    name: 'game',
    title: 'bitty game',
    favicon: './images/game.svg',
    color: '#13e7dd',
    font: 'Orbitron',
  },
  {
    name: 'art',
    title: 'bitty art',
    favicon: './images/art.svg',
    color: '#FF66FF',
    font: 'Megrim',
  },
  {
    name: 'MATH',
    title: 'bitty math',
    favicon: './images/math.svg',
    color: '#90E45E',
    font: 'Roboto',
  },
  {
    name: 'grave',
    title: 'bitty grave',
    favicon: './images/grave.svg',
    color: '#e013e7',
    font: 'Creepster',
  },
]
