const apps = [
  {
    name: 'app',
    title: 'bitty app',
    favicon: '',
    color: '#13e7dd',
    font: 'Press Start 2P',
  },
  {
    name: 'blog',
    title: 'bitty blog',
    favicon: '',
    color: '#009BFF',
    font: 'Share Tech Mono',
  },
  {
    name: 'shop',
    title: 'bitty shop',
    favicon: '',
    color: '#bd6bdd',
    font: 'Monoton',
  },
  {
    name: 'note',
    title: 'bitty note',
    favicon: '',
    color: '#ece63d',
    font: 'Permanent Marker',
  },
  {
    name: 'game',
    title: 'bitty game',
    favicon: '',
    color: '#13e7dd',
    font: 'Orbitron',
  },
  {
    name: 'art',
    title: 'bitty art',
    favicon: '',
    color: '#FF66FF',
    font: 'Megrim',
  },
  {
    name: 'grave',
    title: 'bitty grave',
    favicon: '',
    color: '#e013e7',
    font: 'Creepster',
  },
]
